# Generated by Django 5.0.2 on 2024-05-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_produit_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='totalCde',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
